name: Build-Parfis-and-run-gtestAll

on:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        version: [Release, Debug]
        # os: [ubuntu-latest]
        # version: [Release]

    steps:

    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest rep

    - name: Make build dir
      shell: bash
      run: mkdir build

    - if: ${{ matrix.version=='Release' }}
      name: Build Release
      run: |
        cd build
        cmake ..
        cmake --build . --config Release
        cd ..
      # name: Upload libparfis.so
      # uses: actions/upload-artifact@v2
      # with:
      #   name: libparfis.so  
      #   path: build/lib/parfis/libparfis.so
      #   if-no-files-found: error
      #   retention-days: 1

    - if: ${{ matrix.version=='Debug' }}
      name: Build Debug
      run: |
        cd build
        cmake .. -DBUILD_DEBUG=ON
        cmake --build . --config Debug
        cd ..

    # Running gtestAll
    
    - if: ${{ matrix.version=='Release' && matrix.os=='ubuntu-latest'}} 
      name: gtestAll
      run: build/bin/gtestAll/gtestAll
    
    - if: ${{ matrix.version=='Debug' && matrix.os=='ubuntu-latest'}} 
      name: gtestAlld
      run: build/bin/gtestAll/gtestAlld
    
    - if: ${{ matrix.version=='Release' && matrix.os=='windows-latest'}} 
      name: gtestAll.exe
      run: build/bin/gtestAll/gtestAll.exe

    - if: ${{ matrix.version=='Debug' && matrix.os=='windows-latest'}} 
      name: gtestAlld.exe
      run: build/bin/gtestAll/gtestAlld.exe

    # Runnning python tests

  python-sdist-test:
    runs-on: ubuntu-latest
    name: Test installing Parfis Python source package on Ubuntu
    steps:
    - uses: actions/setup-python@v2
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
        python-version: '3.8'
    - name: Build and install Parfis
      shell: bash
      run: |
        pip install wheel
        cd python-package
        python --version
        python setup.py bdist_wheel
        pip install --force-reinstall -v ./dist/parfis-*.whl
        cd ..
        python -c 'import parfis'