name: Build-Parfis-and-run-gtestAll

on:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:

  build-release-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest rep
    - name: Make build dir, run cmake and make
      shell: bash -l {0}
      run: |
        mkdir build
        cd build
        cmake ..
        make
        cd ..
    - name: Upload libparfis.so
      uses: actions/upload-artifact@v2
      with:
        name: libparfis.so  
        path: build/lib/parfis/libparfis.so
        if-no-files-found: error
        retention-days: 1
    - name: Run gtestAll
      run: build/bin/gtestAll/gtestAll

  build-debug-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest rep
    - name: Make build dir, run cmake and make
      shell: bash -l {0}
      run: |
        mkdir build
        cd build
        cmake .. -DBUILD_DEBUG=ON
        make
    - name: Run gestAlld
      run: build/bin/gtestAll/gtestAlld

  build-release-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest rep
    - name: Make build dir, run cmake and make
      shell: bash - l {0}
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build . --config Release
    - name: Run gtestAll.exe
      run: build/bin/gtestAll/gtestAll.exe

  build-debug-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest rep
    - name: Make build dir, run cmake and make
      shell: bash -l {0}
      run: |
        mkdir build
        cd build
        cmake .. -DBUILD_DEBUG=ON
        cmake --build . --config Debug
    - name: Run gestAlld.exe
      run: build/bin/gtestAll/gtestAlld.exe
