name: Build-Parfis-and-run-gtestAll

on:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:

  build-and-gtest:
  
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        version: [Release, Debug]
        # os: [ubuntu-latest]
        # version: [Release]

    name: Build and run gtestAll
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest rep

    - name: Make build dir
      shell: bash
      run: mkdir build

    - if: ${{ matrix.version=='Release' }}
      name: Build Release
      run: |
        cd build
        cmake ..
        cmake --build . --config Release
        cd ..

    - if: ${{ matrix.version=='Debug' }}
      name: Build Debug
      run: |
        cd build
        cmake .. -DBUILD_DEBUG=ON
        cmake --build . --config Debug
        cd ..

    # Run gtestAll
    
    - if: ${{ matrix.version=='Release' && matrix.os=='ubuntu-latest'}} 
      name: gtestAll
      run: build/bin/gtestAll/gtestAll
    
    - if: ${{ matrix.version=='Debug' && matrix.os=='ubuntu-latest'}} 
      name: gtestAlld
      run: build/bin/gtestAll/gtestAlld
    
    - if: ${{ matrix.version=='Release' && matrix.os=='windows-latest'}} 
      name: gtestAll.exe
      run: build/bin/gtestAll/gtestAll.exe

    - if: ${{ matrix.version=='Debug' && matrix.os=='windows-latest'}} 
      name: gtestAlld.exe
      run: build/bin/gtestAll/gtestAlld.exe

    - if: ${{ matrix.version=='Release' && matrix.os=='ubuntu-latest'}} 
      name: Upload libparfis.so
      uses: actions/upload-artifact@v2
      with:
        name: libparfis.so
        path: build/lib/parfis/libparfis.so
        if-no-files-found: error
        retention-days: 1

    - if: ${{ matrix.version=='Release' && matrix.os=='windows-latest'}} 
      name: Upload parfis.dll
      uses: actions/upload-artifact@v2
      with:
        name: parfis.dll
        path: build/lib/parfis/parfis.dll
        if-no-files-found: error
        retention-days: 1


    # Run python packaging
    # - if: ${{ matrix.version=='Release' && matrix.os=='ubuntu-latest'}}
    #   name: Create pypi package
    #   steps:
    #   - uses: actions/setup-python@v2
    #     with:
    #       submodules: 'true'
    #       python-version: '3.8'


  pypi-and-pytest:
    needs: build-and-gtest
    runs-on: ubuntu-latest
    name: Test installing Parfis Python source package on Ubuntu
    steps:
    - uses: actions/setup-python@v2
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
        python-version: '3.8'

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: libparfis.so
        path: python-package/parfis/clib

    - name: Build and install Parfis
      shell: bash
      run: |
        pip install wheel
        cd python-package
        file ./parfis/clib/libparfis.so
        python --version
        python setup.py bdist_wheel
        pip install --force-reinstall -v ./dist/parfis-*.whl
        cd ..
        python test/pytest/test01.py