name: Build and test
on:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build-release-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest rep
    - name: Make build dir, run cmake and make
      shell: bash
      run: |
        mkdir build
        cd build
        cmake ..
        make
    - name: Run Test
      run: ./build/bin/gtestAll/gtestAll
  build-debug-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest rep
    - name: Make build dir, run cmake and make
      shell: bash
      run: |
        mkdir build
        cd build
        cmake .. -DBUILD_DEBUG=ON
        make
    - name: Run Test
      run: ./build/bin/gtestAll/gtestAlld
  build-release-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest rep
    - name: Make build dir, run cmake and make
      shell: bash
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build . --config Release
    - name: Run Test
      run: ./build/bin/gtestAll/gtestAll.exe
  build-debug-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest rep
    - name: Make build dir, run cmake and make
      shell: bash
      run: |
        mkdir build
        cd build
        cmake .. -DBUILD_DEBUG=ON
        cmake --build . --config Debug
    - name: Run Test
      run: ./build/bin/gtestAll/gtestAlld.exe
