name: Run CMake
on: pull-request-locally
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest rep
    - name: Make build dir, run cmake and make
      shell: bash
      run: |
        mkdir build
        cd build
        cmake ..
        make
    - name: Run Test
      run: ./gtestAll
     
